
export const coffeeList = [
  {
    id: "1",
    imgCoffee: "../coffes/expressoTradicional.png",
    type: ["tradicional"],
    name: "Expresso Tradicional",
    desciption: "O tradicional café feito com água quente e grãos moídos",
    value: "990"
  },
  {
    id: "2",
    imgCoffee: "/assets/png/coffes/expressoAmericano.png",
    type: ["tradicional"],
    name: "Expresso Americano",
    desciption: "Expresso diluído, menos intenso que o tradicional",
    value: "990",
  },
  {
    id: "3",
    imgCoffee: "/assets/png/coffes/expressoCremoso.png",
    type: ["tradicional"],
    name: "Expresso Cremoso",
    desciption: "ECafé expresso tradicional com espuma cremosa",
    value: "990",
  },
  {
    id: "4",
    imgCoffee:
      "../assets/png/coffes//assets/png/coffes/xpressoAmericano.png.png",
    type: ["tradicional", "gelado"],
    name: "Expresso Gelado",
    desciption: "Bebida preparada com café expresso e cubos de gelo",
    value: "990",
  },
  {
    id: "5",
    imgCoffee: "/assets/png/coffes/cofecomleite.png",
    type: ["tradicional", "com leite"],
    name: "Café com Leite",
    desciption: "Meio a meio de expresso tradicional com leite vaporizado",
    value: "990",
  },
  {
    id: "6",
    imgCoffee: "/assets/png/coffes/latte.png",
    type: ["tradicional", "com leite"],
    name: "Latte",
    desciption:
      "Uma dose de café expresso com o dobro de leite e espuma cremosa",
    value: "990",
  },
  {
    id: "7",
    imgCoffee: "/assets/png/coffes/capuccino.png",
    type: ["tradicional", "com leite"],
    name: "Capuccino",
    desciption:
      "Bebida com canela feita de doses iguais de café, leite e espuma",
    value: "990",
  },
  {
    id: "8",
    imgCoffee: "/assets/png/coffes/mocchiato.png",
    type: ["tradicional", "com leite"],
    name: "Mocchiato",
    desciption: "Café expresso misturado com um pouco de leite quente e espuma",
    value: "990",
  },
  {
    id: "9",
    imgCoffee: "/assets/png/coffes/mocaccino.png",
    type: ["tradicional", "com leite"],
    name: "Mocaccino",
    desciption: "Café expresso com calda de chocolate, pouco leite e espuma",
    value: "990",
  },
  {
    id: "10",
    imgCoffee: "/assets/png/coffes/chocolateQuente.png",
    type: ["especial", "com leite"],
    name: "Chocolate Quente",
    desciption: "Bebida feita com chocolate dissolvido no leite quente e café",
    value: "990",
  },
  {
    id: "11",
    imgCoffee: "/assets/png/coffes/cubano.png",
    type: ["especial", "alcoólico", "gelado"],
    name: "Cubano",
    desciption:
      "Drink gelado de café expresso com rum, creme de leite e hortelã",
    value: "990",
  },
  {
    id: "12",
    imgCoffee: "/assets/png/coffes/havaiano.png",
    type: ["especial"],
    name: "Havaiano",
    desciption: "Bebida adocicada preparada com café e leite de coco",
    value: "990",
  },
  {
    id: "13",
    imgCoffee: "/assets/png/coffes/arabe.png",
    type: ["especial"],
    name: "Árabe",
    desciption: "Bebida preparada com grãos de café árabe e especiarias",
    value: "990",
  },
  {
    id: "14",
    imgCoffee: "/assets/png/coffes/irlandes.png",
    type: ["especial", "alcoólico"],
    name: "irlandês",
    desciption: "Bebida a base de café, uísque irlandês, açúcar e chantilly",
    value: "990",
  },
];
